"""drop base, create users

Revision ID: c492f7fa7eac
Revises: 300bc24efed6
Create Date: 2022-12-11 11:17:55.409231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c492f7fa7eac"
down_revision = "300bc24efed6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=True),
        sa.Column("username", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.drop_table("base")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "base",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=32), autoincrement=False, nullable=True),
        sa.Column(
            "username", sa.VARCHAR(length=32), autoincrement=False, nullable=True
        ),
        sa.Column("email", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="base_pkey"),
        sa.UniqueConstraint("username", name="base_username_key"),
    )
    op.drop_table("user")
    # ### end Alembic commands ###
