# Generated by Django 4.1.4 on 2023-01-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "username",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="username"
                    ),
                ),
                (
                    "email",
                    models.CharField(max_length=64, unique=True, verbose_name="email"),
                ),
                ("address", models.TextField(blank=True, verbose_name="address")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "website",
                    models.CharField(blank=True, max_length=64, verbose_name="website"),
                ),
                (
                    "company",
                    models.CharField(blank=True, max_length=64, verbose_name="company"),
                ),
            ],
        ),
    ]
